version: "3"
services:
  docker-mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  spring-boot-demo-1:
    image: spring-boot-demo-1
    restart: always
    ports:
      - "8088:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/database?autoReconnect=true&useSSL=false
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - docker-mysql
volumes:
  mysql-data: